### PR TITLE
lib: Split checkMkDerivationFor into multiple functions

### PR DESCRIPTION
**Pull request by jtojnar**
This will allow us to reuse it for other package sets like Python.

cc @rmcgibbo

### CODE REVIEW

**Comment by rmcgibbo** [comment]
This looks good to me. If you want to add the feature of passing the originalDrv to the check function into this PR too, I can rebase #15 on top of this.

**Comment by jtojnar** [comment]
Done.

**Review by rmcgibbo — APPROVED** [review]

**Comment by rmcgibbo** [comment]
Cool. Once this is merged, I'll rebase #15.

**Comment by jtojnar** [comment]
Done. Note also the changed name of the `drv` argument to `drvArgs`.

**Pull request merged**
