### PR TITLE
Fix example command

### PR DESCRIPTION
**Pull request by SuperSandro2000**
See https://github.com/NixOS/nix/issues/5081

### CODE REVIEW

**Comment by jtojnar** [comment]
These instructions are for stable Nix. For unstable, you will need to use the second command. Or does stable Nix now include that?

**Comment by jtojnar** [comment]
Unless stable Nix supports this command, we either need to clarify that this command is for stable Nix, or add a third option for unstable Nix without flakes.

**Comment by SuperSandro2000** [comment]
Added that.

**Comment by jtojnar** [comment]
Thanks.

**Pull request merged**
